version: '3'

services:
  #Un conteneur pour la base de données
  db:
    container_name: "mariadb"
    image: mariadb:latest 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "./mariadb/:/var/lib/mysql"
    networks:
      - test-dipli
  #Un conteneur pour l'adminer, pas forcément nécéssaire mais c'est une habitude
  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - test-dipli
  #Un conteneur pour php
  php:
    container_name: "php-fpm"
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - test-dipli
  #Un conteneur nginx
  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - test-dipli
networks:
  test-dipli:
