name: Docker images

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: find infra
    - name: Build docker
      working-directory: infra
      run: docker-compose -p dipli up -d --build
    - name: Init DB
      run: docker-compose -p dipli exec php-fpm php bin/console doctrine:schema:create
    - name: Load Fixture
      run: docker-compose -p dipli exec php-fpm php bin/console doctrine:fixture:load
      
